# Generated by Django 4.2.10 on 2025-04-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('about', models.TextField()),
                ('subhead', models.TextField()),
                ('about2', models.TextField()),
            ],
        ),
    ]
