# Generated by Django 4.2.10 on 2025-04-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_verificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginformation',
            name='local_government_area',
        ),
        migrations.AddField(
            model_name='shippinginformation',
            name='country',
            field=models.CharField(default='World', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippinginformation',
            name='street2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
