# Generated by Django 4.2.10 on 2025-04-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_shippinginformation_local_government_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginformation',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
