# Generated by Django 4.2.10 on 2025-04-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_shippinginformation_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship',
        ),
        migrations.AddField(
            model_name='order',
            name='ship_p1',
            field=models.TextField(default='strret1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ship_p2',
            field=models.TextField(default='street2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ship_p3',
            field=models.TextField(default='street3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=20)),
                ('unit_price', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
            ],
        ),
    ]
