# Generated by Django 4.2.10 on 2025-04-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_order_details_remove_order_ship_order_ship_p1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='72727', max_length=30),
            preserve_default=False,
        ),
    ]
