# Generated by Django 4.2.10 on 2025-04-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hasPaid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
