# Generated by Django 4.2.10 on 2025-04-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_order_haspaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
        migrations.AddField(
            model_name='order',
            name='successful',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
